### PR TITLE
Fix extension WebUSB permission issue

### LINKED ISSUE #1045: Extension throws LedgerNoDeviceSelected
Trying to use ledger in extension always throws LedgerNoDeviceSelected. The reason seems to be that background page can't ask user to give permission to selected USB device; and we run saga in background page.

One potential solution is to ask user for USB permission in the popup, before dispatching to saga:
```tsx
onClick={async () => {
  if (await TransportWebUSB.isSupported()) await TransportWebUSB.create()
  dispatch(importAccountsActions.enumerateAccountsFromLedger())
}}
```

But that actually doesn't work, because default popup ALSO can't ask for permission. It does work in the other kind of popup tho:
```ts
chrome.windows.create({
  url: location.href,
  type: 'popup',
  width: 500,
  height: 600,
})
```
https://github.com/oasisprotocol/oasis-wallet-ext/blob/990a8c78999a2c594d2f0a11991a73a5ca214f9f/src/utils/ledger.js#L28 does this

Note: I only checked this in Chrome, with manifest v2

Debugging note: after granting USB permission you can remove it from extension in chrome://settings/content/usbDevices?search=usb

### PR DESCRIPTION
**Pull request by buberdds**
Fixes #1045
During sync meeting we decided to go with a popup like in a current ext.
Screenshot 2022-10-12 at 18 27 51
Screenshot 2022-10-12 at 18 28 06
Screenshot 2022-10-12 at 18 28 56
Screenshot 2022-10-12 at 18 29 04
Screenshot 2022-10-12 at 18 29 13

error:
Screenshot 2022-11-08 at 13 14 15

### CODE REVIEW

File: src/app/pages/OpenWalletPage/webextension.tsx [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import React from 'react'
+import { openTab } from 'utils/webextension'
+import { SelectOpenMethod } from './'
+
+export function OpenWalletPageWebExtension() {
+  return (
+    <SelectOpenMethod webExtensionLedgerAccess={() => openTab(`${window.location.href}/connect-device`)} />
```
[the remark this answers is not in the document]
Comment (buberdds) [reply src/app/pages/OpenWalletPage/webextension.tsx]: None of `useLocation, useNavigation, useHref, useResolvedPath` hooks return a value of `window.location.href` which I need here `chrome-extension://<extension_id>/popup.<hash>.html#/open-wallet/connect-device`. Didn't find alternatives for setting base href in popup.html as well. Any other idea?

File: src/index.tsx [hunk 2]
```diff
@@ -29,20 +27,20 @@ import './locales/i18n'
...
   <Provider store={store}>
     <ThemeProvider>
       <HelmetProvider>
-        <BrowserRouter>
-          <React.StrictMode>
-            <App />
-          </React.StrictMode>
-        </BrowserRouter>
+        <React.StrictMode>
+          <RouterProvider router={router} />
```
[the remark this answers is not in the document]
Comment (lukaw3d) [reply src/index.tsx:42]: Hm. Previous extension code generated links like `<a href="#/create-wallet">` that navigated to `#/create-wallet`. Now it generates `<a href="/create-wallet">` and navigates to `#/create-wallet`. Middle clicking links with hash-router now opens a broken path.

Not sure if this is an upstream issue or misconfiguration

[the remark this answers is not in the document]
Comment (lukaw3d) [reply src/index.tsx:42]: They don't have a single test for https://github.com/remix-run/react-router/search?q=createHashRouter :angry: and this poop has 8 million weekly downloads

[the remark this answers is not in the document]
Comment (lukaw3d) [reply src/index.tsx:42]: Fixed by https://github.com/remix-run/react-router/pull/9409 in `react-router-dom@pre` release

File: src/app/pages/OpenWalletPage/webextension.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (lukaw3d) [reply src/app/pages/OpenWalletPage/webextension.tsx]: If react-router wasn't broken `useHref('connect-device')` and `useHref('/open-wallet/connect-device')` would return `#/open-wallet/connect-device` in a HashRouter. And then reliably combined with `window.location.pathname`

File: src/app/pages/ConnectDevicePage/index.tsx [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+              justify="center"
+            >
+              <Spinner size="medium" />
+            </Box>
+          )}
+          {connection === 'connected' && (
+            <ConnectionStatusIcon label={t('ledger.extension.succeed', 'Device connected')} />
+          )}
+          {connection === 'error' && (
+            <ConnectionStatusIcon success={false} label={t('ledger.extension.failed', 'Connection failed')} />
```
Comment (lukaw3d) [inline src/app/pages/ConnectDevicePage/index.tsx:104]: Errors aren't as good as before

| Before - Firefox extension | After |
| --- | --- |
| image | image |

| Before - Chrome with blocked webusb | After |
| --- | --- |
| Peek 2022-10-26 02-02 | Peek 2022-10-26 02-00 |

File: src/app/pages/ConnectDevicePage/index.tsx [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+                opacity: 'medium',
+              }}
+              align="center"
+              justify="center"
+            >
+              <Spinner size="medium" />
+            </Box>
+          )}
+          {connection === 'connected' && (
+            <ConnectionStatusIcon label={t('ledger.extension.succeed', 'Device connected')} />
```
Comment (lukaw3d) [inline src/app/pages/ConnectDevicePage/index.tsx:101]: Extra popup should probably automatically close after this

File: src/app/pages/OpenWalletPage/index.tsx [hunk 5]
```diff
@@ -33,9 +44,18 @@ export function SelectOpenMethod() {
...
-        <span>
-          <ButtonLink to="ledger" label={t('openWallet.method.ledger', 'Ledger')} primary />
-        </span>
+        {webExtensionLedgerAccess ? (
+          <Button
+            style={{ width: 'fit-content' }}
+            onClick={webExtensionLedgerAccess}
+            label={t('ledger.extension.grantAccess', 'Grant access to your Ledger')}
+            primary
+          />
```
Comment (lukaw3d) [inline src/app/pages/OpenWalletPage/index.tsx:53]: This flow should only be needed the first time for each unpaired ledger device, not every time. Background page already has the needed permissions.

Comment (lukaw3d) [reply src/app/pages/OpenWalletPage/index.tsx:53]: How about on click: attempt to get a device and if it fails openLedgerAccessPopup

Comment (buberdds) [reply src/app/pages/OpenWalletPage/index.tsx]: Can you share more details? Do you want to dispatch saga action first and handle "LedgerNoDeviceSelected" differently or there is some way to get a device and checked if it's paired?

Comment (lukaw3d) [reply src/app/pages/OpenWalletPage/index.tsx]: I think just `try { await TransportWebUSB.create(); to="ledger" } catch (e) { openLedgerAccessPopup() }`

Comment (buberdds) [reply src/app/pages/OpenWalletPage/index.tsx]: If we want to create usb transport  here we will have to close it in React component as well to avoid `USB Transport error: Failed to execute 'claimInterface' on 'USBDevice': Unable to claim interface.` At this point everything looks fine, but when I will revoke usb access I go through process again and it will end up with `USB Transport error: Failed to execute 'open' on 'USBDevice': The device was disconnected..`.

File: src/app/pages/OpenWalletPage/__tests__/index.test.tsx [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+  })
+
+  it('should render component', async () => {
+    const { container } = await waitFor(() => renderComponent())
+
+    expect(container).toMatchSnapshot()
+  })
+
+  it('should render component with an access button', async () => {
+    await waitFor(() => renderComponent(() => {}))
```
Comment (lukaw3d) [inline src/app/pages/OpenWalletPage/__tests__/index.test.tsx:40]: ??

waitFor runs the function multiple times until expect() inside is successful. So this renders infinite number of components, or I guess it does nothing because there are no expects inside

File: src/app/pages/OpenWalletPage/__tests__/index.test.tsx [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+
+    expect(screen.queryByText('openWallet.method.ledger')).not.toBeInTheDocument()
+    expect(screen.getByText('ledger.extension.grantAccess')).toBeInTheDocument()
```
Comment (lukaw3d) [inline src/app/pages/OpenWalletPage/__tests__/index.test.tsx:43]: I'd merge this into `should render component` test

File: src/app/pages/OpenWalletPage/__tests__/index.test.tsx [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+  it('should render variant with web usb support', async () => {
+    jest.mocked(canAccessNavigatorUsb).mockResolvedValue(true)
+    const { rerender } = await waitFor(() => renderComponent())
+    rerender(
+      <MemoryRouter>
+        <SelectOpenMethod />
+      </MemoryRouter>,
+    )
+
+    expect(screen.queryByText('errors.usbTransportNotSupported')).not.toBeInTheDocument()
```
Comment (lukaw3d) [inline src/app/pages/OpenWalletPage/__tests__/index.test.tsx:65]: Add a test that establishes `screen.queryByText('errors.usbTransportNotSupported')` can sometimes be in the document. Otherwise `not.toBeInTheDocument` never detects if we renamed it, and error actually was shown

File: src/utils/webextension.ts [hunk 9]
```diff
@@ -0,0 +1,25 @@
...
+
+const getExtensionUrl = (path: string) =>
+  browser.runtime.getURL(`${browser.runtime.getManifest()?.browser_action?.default_popup}${path}`)
+
+const openPopup = (path: string, dimensions: Dimensions) => {
+  const existingPopupWindow = browser.extension.getViews().find(window => window.location.hash === path)
+
+  if (existingPopupWindow) {
+    existingPopupWindow.close()
+  }
```
[the remark this answers is not in the document]
Comment (buberdds) [reply src/utils/webextension.ts]: - yes, extension is using HashRouter
- added a guard
- it does not have subroutes

File: src/app/pages/OpenWalletPage/__tests__/index.test.tsx (hunk 7 above)
Comment (buberdds) [reply src/app/pages/OpenWalletPage/__tests__/index.test.tsx:43]: Why when it's an opposite case to what default snapshot is rendering?

File: src/app/pages/OpenWalletPage/__tests__/index.test.tsx (hunk 8 above)
Comment (buberdds) [reply src/app/pages/OpenWalletPage/__tests__/index.test.tsx]: That is handled by snapshot already.

File: src/utils/webextension.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (lukaw3d) [reply src/utils/webextension.ts]: More robust than implicitly encoding HashRouter and adding a guard:
`.find(window => window.location.href === getPopupUrl(path))`

File: src/utils/webextension.ts [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+  browser.windows.create({
```
[the remark this answers is not in the document]
Comment (lukaw3d) [reply src/utils/webextension.ts:17]: No, it just might be annoying if we later need to make it async to use the value `browser.windows.create` resolves to, or catch the promise rejection

File: src/app/pages/OpenWalletPage/__tests__/index.test.tsx (hunk 7 above)
Comment (lukaw3d) [reply src/app/pages/OpenWalletPage/__tests__/index.test.tsx:43]: Oh, oops :O

File: src/app/pages/OpenWalletPage/__tests__/index.test.tsx (hunk 8 above)
Comment (lukaw3d) [reply src/app/pages/OpenWalletPage/__tests__/index.test.tsx]: Yep yep, I'd simply add `expect(screen.getByText('errors.usbTransportNotSupported')).toBeInTheDocument()` after snapshot

File: src/app/pages/ConnectDevicePage/index.tsx (hunk 4 above)
Comment (lukaw3d) [reply src/app/pages/ConnectDevicePage/index.tsx:101]: Not sure if you changed this in an odd way: popup1 closes after returning to it, after success
popup1-disappears

File: src/app/pages/OpenWalletPage/index.tsx (hunk 5 above)
Comment (lukaw3d) [reply src/app/pages/OpenWalletPage/index.tsx]: Alright I am able to reproduce this
```tsx
  try {
    await (await TransportWebUSB.create()).close()
    navigate('/open-wallet/ledger')
  } catch (e) {
    webExtensionLedgerAccess()
  }
```

what's very odd is that it works after reloading background page, as if `close()` doesn't fully reset device communication
- start with extension having USB permission
- enumerate accounts **works**, cancel
- remove USB permission
- connect ledger flow, enumerate accounts **does not work**, cancel
- reload background page
- enumerate accounts works, cancel
- remove USB permission
- reload background page
- connect ledger flow, enumerate accounts **works**, cancel

File: src/app/pages/ConnectDevicePage/index.tsx (hunk 3 above)
Comment (lukaw3d) [reply src/app/pages/ConnectDevicePage/index.tsx:104]: | Updated error in Firefox (reproduced by temporarily installing ext in `about:debugging#/runtime/this-firefox`) | Chrome with blocked webusb is still stuck (reproduced with `Don't allow sites to connect to USB devices` in chrome://settings/content/usbDevices) |
| --- | --- |
| Screenshot from 2022-11-08 03-40-27  | Peek 2022-11-08 03-47  |

Comment (buberdds) [reply src/app/pages/ConnectDevicePage/index.tsx:104]: No specific error is thrown in this case just generic "No device selected". I will show ErrorFormatter in this case

File: src/app/pages/ConnectDevicePage/index.tsx (hunk 4 above)
Comment (buberdds) [reply src/app/pages/ConnectDevicePage/index.tsx:107]: checked both dev and prod builds and I cannot repro this

File: src/utils/webextension.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (lukaw3d) [reply src/utils/webextension.ts]: (`if (path` guard isn't needed anymore)

**Review by lukaw3d — APPROVED** [review]
