### PR TITLE
fix: protect validator-media-info from xss attacks

### LINKED ISSUE #185: Validator information allows XSS through URLs
If validator has a website link `validator.media.website_link = 'javascript:alert(1)'` it executes when user middle-clicks the website link

Minimal code to reproduce:
```jsx
<ValidatorMediaInfo mediaInfo={ { website_link: 'javascript:alert(1)' } } />
```

Blocking https://github.com/oasisprotocol/oasis-wallet-web/issues/181

### PR DESCRIPTION
**Pull request by Esya**
Fixes #185

### CODE REVIEW

**Review by lukaw3d — APPROVED** [review]

File: src/app/pages/StakingPage/Features/ValidatorMediaInfo/index.tsx [hunk 1]
```diff
@@ -17,8 +18,12 @@ export const ValidatorMediaInfo = memo((props: Props) => {
   return (
     <>
       {info.email_address && <MediaButton href={`mailto:${info.email_address}`} icon={<MailOption />} />}
```
Comment (lukaw3d) [inline src/app/pages/StakingPage/Features/ValidatorMediaInfo/index.tsx:20]: Is the email address validated anywhere in the stack? Otherwise some mail clients are vulnerable to autoattaching files with `mailto:?attach=..`

(https://www.nds.ruhr-uni-bochum.de/media/nds/veroeffentlichungen/2020/08/15/mailto-paper.pdf)
