### PR TITLE
Detect invalid private keys when importing them

### LINKED ISSUE #960: Can we detect typos in private key?
If user imports `oPNmZybIOymrQCpCGGICczsaopANP02kwOhCyxETXljLLmRChL1QJGzJq3Pf3i+dFBN+peIK2vQ3Ew0wSQbp3g==` it opens `oasis1qpd0sz9s0s5ewmmmgyn7h44hg6yygv2reyr9mmre` and they can sign transactions.

If user imports `aaamZybIOymrQCpCGGICczsaopANP02kwOhCyxETXljLLmRChL1QJGzJq3Pf3i+dFBN+peIK2vQ3Ew0wSQbp3g==` it opens `oasis1qpd0sz9s0s5ewmmmgyn7h44hg6yygv2reyr9mmre` and they will only get an error when trying to sign a transaction: `signature verification failed`

### PR DESCRIPTION
**Pull request by csillag**
Fixes #960.

### CODE REVIEW

File: src/app/lib/key.ts [hunk 1]
```diff
@@ -9,7 +20,11 @@ export class OasisKey {
     if (key.length === 32) {
       return nacl.sign.keyPair.fromSeed(key).secretKey
     } else if (key.length === 64) {
-      return nacl.sign.keyPair.fromSecretKey(key).secretKey
+      const keyPair = nacl.sign.keyPair.fromSecretKey(key)
+      if (!canSignWith(keyPair)) {
+        throw new Error('Invalid private key. There must a typo somewhere..')
```
Comment (pro-wh) [inline src/app/lib/key.ts:25]: extra dot at the end?

File: src/app/lib/key.ts [hunk 2]
```diff
@@ -1,5 +1,16 @@
...
 
+/**
+ * Verify if a key pair is actually usable for signatures
+ */
+function canSignWith(keyPair: nacl.SignKeyPair) {
+  const { secretKey, publicKey } = keyPair
+  const testMessage = Uint8Array.from([1, 2, 3])
+  const signedTestMessage = nacl.sign(testMessage, secretKey)
+  const testDecoded = nacl.sign.open(signedTestMessage, publicKey)
+  return testDecoded && testDecoded.toString() === testMessage.toString()
```
Comment (pro-wh) [inline src/app/lib/key.ts:11]: :information_source: reason for the `testDecoded &&`

> nacl.sign.open(signedMessage, publicKey)
>
> Verifies the signed message and returns the message without signature.
>
> Returns null if verification failed.

the `.toString()` gets us an easily comparable `1,2,3`

**Review by pro-wh — APPROVED** [review]
reasonable way to check

File: src/app/lib/key.ts (hunk 1 above)
Comment (csillag) [reply src/app/lib/key.ts:25]: Removed.

Comment (pro-wh) [reply src/app/lib/key.ts:25]: thanks

File: src/app/lib/key.ts (hunk 2 above)
Comment (csillag) [reply src/app/lib/key.ts:11]: SInce the returned value can also be `null`, I can't simply call `.toString()`, but `?.toString()` works, so I got rid of `testDecoded &&`.

Comment (pro-wh) [reply src/app/lib/key.ts]: oops I mean that bit about the toString as a separate note.

could also do `'' + testDecoded` or `String(testDecoded)`

Comment (csillag) [reply src/app/lib/key.ts]: So instead of `testDecoded?.toString() === testMessage.toString()`, would you prefer `testDecoded + '' === testMessage + ''` ?

Comment (pro-wh) [reply src/app/lib/key.ts]: really the `testDecoded &&` was fine imo

Comment (csillag) [reply src/app/lib/key.ts]: The linter actually came up with this:
```
return `${testDecoded}` === `${testMessage}`
```
This version is probably marginally more efficient (with the string building), and can also handle the null without an extra check.

Comment (pro-wh) [reply src/app/lib/key.ts]: that sounds fine too

Comment (csillag) [reply src/app/lib/key.ts]: OK, so let's go with that, and I'm marking this conversation as resolved.

**Review by lukaw3d — COMMENTED** [review]
Nice

File: src/app/lib/key.ts [hunk 3]
```diff
@@ -1,5 +1,16 @@
...
 
+/**
+ * Verify if a key pair is actually usable for signatures
+ */
+function canSignWith(keyPair: nacl.SignKeyPair) {
+  const { secretKey, publicKey } = keyPair
+  const testMessage = Uint8Array.from([1, 2, 3])
+  const signedTestMessage = nacl.sign(testMessage, secretKey)
+  const testDecoded = nacl.sign.open(signedTestMessage, publicKey)
+  return `${testDecoded}` === `${testMessage}`
```
[the remark this answers is not in the document]
Comment (csillag) [reply src/app/lib/key.ts:11]: OK, this has been improved in https://github.com/oasisprotocol/oasis-wallet-web/pull/1009
